# Generated by Django 3.1.6 on 2021-04-03 11:37

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='service',
            name='disponibilite',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='service',
            name='principal_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
