# Generated by Django 3.1.6 on 2021-04-03 14:33

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_service_principal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), null=True, srid=4326),
        ),
    ]
