# Generated by Django 3.1.6 on 2021-04-06 15:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Latitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
