# Generated by Django 3.1.6 on 2021-04-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_service_principal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='principal_image',
        ),
    ]
