# Generated by Django 3.1.6 on 2021-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_service_principal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='Adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prod',
            name='Shop',
            field=models.CharField(default='', max_length=200),
        ),
    ]
