# Generated by Django 3.1.6 on 2021-04-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_service_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Adress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
