# Generated by Django 3.1.6 on 2021-04-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_prod_name_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
