# Generated by Django 3.1.6 on 2021-04-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210414_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_couverture',
            field=models.ImageField(default='default - Copie.jpg', upload_to='profile_pics'),
        ),
    ]
