# Generated by Django 3.1.6 on 2021-04-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_image_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_service',
            field=models.ImageField(default='default - Copie.jpg', upload_to='profile_pics'),
        ),
    ]
