# Generated by Django 3.1.6 on 2021-05-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210518_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
