# Generated by Django 3.1.6 on 2021-05-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
