# Generated by Django 3.1.6 on 2021-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Latitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
